## Load movies data and display statistics for the dataset

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('../archive rotten tomatoes/rotten_tomatoes_movies.csv')#, nrows = 1000)
df.head()

rotten_tomatoes_link  \
0                              m/0814255   
1                              m/0878835   
2                                   m/10   
3                 m/1000013-12_angry_men   
4  m/1000079-20000_leagues_under_the_sea   

                                         movie_title  \
0  Percy Jackson & the Olympians: The Lightning T...   
1                                        Please Give   
2                                                 10   
3                    12 Angry Men (Twelve Angry Men)   
4                       20,000 Leagues Under The Sea   

                                          movie_info  \
0  Always trouble-prone, the life of teenager Per...   
1  Kate (Catherine Keener) and her husband Alex (...   
2  A successful, middle-aged Hollywood songwriter...   
3  Following the closing arguments in a murder tr...   
4  In 1866, Professor Pierre M. Aronnax (Paul Luk...   

                                   critics_consensus content_rating  \
0  Though it may seem like just another Harry Pot...             PG   
1  Nicole Holofcener's newest might seem slight i...              R   
2  Blake Edwards' bawdy comedy may not score a pe...              R   
3  Sidney Lumet's feature debut is a superbly wri...             NR   
4  One of Disney's finest live-action adventures,...              G   

                                              genres          directors  \
0  Action & Adventure, Comedy, Drama, Science Fic...     Chris Columbus   
1                                             Comedy  Nicole Holofcener   
2                                    Comedy, Romance      Blake Edwards   
3                                    Classics, Drama       Sidney Lumet   
4           Action & Adventure, Drama, Kids & Family  Richard Fleischer   

                                      authors  \
0  Craig Titley, Chris Columbus, Rick Riordan   
1                           Nicole Holofcener   
2                               Blake Edwards   
3                               Reginald Rose   
4                                 Earl Felton   

                                              actors original_release_date  \
0  Logan Lerman, Brandon T. Jackson, Alexandra Da...            2010-02-12   
1  Catherine Keener, Amanda Peet, Oliver Platt, R...            2010-04-30   
2  Dudley Moore, Bo Derek, Julie Andrews, Robert ...            1979-10-05   
3  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....            1957-04-13   
4  James Mason, Kirk Douglas, Paul Lukas, Peter L...            1954-01-01   

   ...      production_company  tomatometer_status tomatometer_rating  \
0  ...        20th Century Fox              Rotten               49.0   
1  ...  Sony Pictures Classics     Certified-Fresh               87.0   
2  ...             Waner Bros.               Fresh               67.0   
3  ...    Criterion Collection     Certified-Fresh              100.0   
4  ...                  Disney               Fresh               89.0   

  tomatometer_count  audience_status  audience_rating audience_count  \
0             149.0          Spilled             53.0       254421.0   
1             142.0          Upright             64.0        11574.0   
2              24.0          Spilled             53.0        14684.0   
3              54.0          Upright             97.0       105386.0   
4              27.0          Upright             74.0        68918.0   

   tomatometer_top_critics_count  tomatometer_fresh_critics_count  \
0                             43                               73   
1                             44                              123   
2                              2                               16   
3                              6                               54   
4                              5                               24   

   tomatometer_rotten_critics_count  
0                                76  
1                                19  
2                                 8  


In [5]:
df.columns

Index(['rotten_tomatoes_link', 'movie_title', 'movie_info',
       'critics_consensus', 'content_rating', 'genres', 'directors', 'authors',
       'actors', 'original_release_date', 'streaming_release_date', 'runtime',
       'production_company', 'tomatometer_status', 'tomatometer_rating',
       'tomatometer_count', 'audience_status', 'audience_rating',
       'audience_count', 'tomatometer_top_critics_count',
       'tomatometer_fresh_critics_count', 'tomatometer_rotten_critics_count'],
      dtype='object')

In [6]:
df.describe(include='all')

rotten_tomatoes_link movie_title  \
count                 17712       17712   
unique                17712       17106   
top               m/0814255      Hamlet   
freq                      1           6   
mean                    NaN         NaN   
std                     NaN         NaN   
min                     NaN         NaN   
25%                     NaN         NaN   
50%                     NaN         NaN   
75%                     NaN         NaN   
max                     NaN         NaN   

                                               movie_info  \
count                                               17391   
unique                                              17389   
top     Wisecracking mercenary Deadpool meets Russell,...   
freq                                                    2   
mean                                                  NaN   
std                                                   NaN   
min                                                   NaN   
25%                                                   NaN   
50%                                                   NaN   
75%                                                   NaN   
max                                                   NaN   

                                        critics_consensus content_rating  \
count                                                9134          17712   
unique                                               9132              6   
top     High Life is as visually arresting as it is ch...              R   
freq                                                    2           6377   
mean                                                  NaN            NaN   
std                                                   NaN            NaN   
min                                                   NaN            NaN   
25%                                                   NaN            NaN   
50%                                                   NaN            NaN   
75%                                                   NaN            NaN   
max                                                   NaN            NaN   

       genres       directors      authors         actors  \
count   17693           17518        16170          17360   
unique   1106            8933        12989          17330   
top     Drama  Clint Eastwood  Woody Allen  Werner Herzog   
freq     1887              38           33              4   
mean      NaN             NaN          NaN            NaN   
std       NaN             NaN          NaN            NaN   
min       NaN             NaN          NaN            NaN   
25%       NaN             NaN          NaN            NaN   
50%       NaN             NaN          NaN            NaN   
75%       NaN             NaN          NaN            NaN   
max       NaN             NaN          NaN            NaN   

       original_release_date  ...  production_company  tomatometer_status  \
count                  16546  ...               17213               17668   
unique                  5804  ...                3046                   3   
top               2002-01-01  ...  Paramount Pictures              Rotten   
freq                      29  ...                 517                7565   
mean                     NaN  ...                 NaN                 NaN   
std                      NaN  ...                 NaN                 NaN   
min                      NaN  ...                 NaN                 NaN   
25%                      NaN  ...                 NaN                 NaN   
50%                      NaN  ...                 NaN                 NaN   
75%                      NaN  ...                 NaN                 NaN   
max                      NaN  ...                 NaN                 NaN   

       tomatometer_rating tomatometer_count  audience_status  audience_rating  \
count        17668.000000      17668.000000            17264     17416.000000   
unique                Na

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17712 entries, 0 to 17711
Data columns (total 22 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   rotten_tomatoes_link              17712 non-null  object 
 1   movie_title                       17712 non-null  object 
 2   movie_info                        17391 non-null  object 
 3   critics_consensus                 9134 non-null   object 
 4   content_rating                    17712 non-null  object 
 5   genres                            17693 non-null  object 
 6   directors                         17518 non-null  object 
 7   authors                           16170 non-null  object 
 8   actors                            17360 non-null  object 
 9   original_release_date             16546 non-null  object 
 10  streaming_release_date            17328 non-null  object 
 11  runtime                           17398 non-null  float64
 12  prod

## Cleaning data

#### genres (One-Hot Encoding)

In [8]:
df['genres'] = df['genres'].apply(lambda x: [] if pd.isna(x) else [genre.strip() for genre in x.split(',')])
df_encoded = df['genres'].apply(lambda x: pd.Series([1] * len(x), index=x)).fillna(0).astype(int, errors='ignore')  # One-Hot Encoding
df = pd.concat([df, df_encoded], axis=1)

#### content_rating (One-Hot Encoding)

In [9]:
df = pd.get_dummies(df, columns=['content_rating'], prefix='content_rating')    # One-Hot Encoding

content_rating_columns = df.filter(like='content_rating')
for col in content_rating_columns:
    df[col] = df[col].astype(int)

#### tomatometer_status

In [10]:
def clean_tomatometer_status(status):
    if status == 'Rotten':
        return 0
    elif status == 'Fresh':
        return 1
    elif status == 'Certified-Fresh':
        return 2
    return status
df.loc[:, 'tomatometer_status'] = df['tomatometer_status'].apply(lambda x: clean_tomatometer_status(x))
df.tomatometer_status.value_counts()

tomatometer_status
0.0    7565
1.0    6844
2.0    3259
Name: count, dtype: int64

#### tomatometer_rating, audience_rating, audience_status

In [11]:
df = df.dropna(subset=['tomatometer_rating', 'audience_rating', 'audience_status']) # drop rows containing NaN

In [12]:
df.loc[:, 'audience_status'] = df['audience_status'].apply(lambda x: 1 if x == 'Upright' else 0 if x == 'Spilled' else x )
df.audience_status.value_counts()

audience_status
1    9385
0    7870
Name: count, dtype: int64

In [13]:
#print(df.columns)
used_features = [
    'tomatometer_status', 'tomatometer_rating', 'audience_status', 'audience_rating', 
    'Action & Adventure', 'Comedy', 'Drama', 'Science Fiction & Fantasy',
    'Romance', 'Classics', 'Kids & Family', 'Mystery & Suspense', 'Western',
    'Art House & International', 'Horror', 'Faith & Spirituality',
    'Animation', 'Documentary', 'Special Interest',
    'Musical & Performing Arts', 'Sports & Fitness', 'Television',
    'Cult Movies', 'Anime & Manga', 'Gay & Lesbian', 
    'content_rating_G', 'content_rating_NC17', 'content_rating_NR', 'content_rating_PG', 'content_rating_PG', 'content_rating_R']
df[ ['rotten_tomatoes_link']+used_features ]

rotten_tomatoes_link tomatometer_status  \
0                                  m/0814255                0.0   
1                                  m/0878835                2.0   
2                                       m/10                1.0   
3                     m/1000013-12_angry_men                2.0   
4      m/1000079-20000_leagues_under_the_sea                1.0   
...                                      ...                ...   
17707                            m/zoot_suit                0.0   
17708                             m/zootopia                2.0   
17709                      m/zorba_the_greek                1.0   
17710                                 m/zulu                1.0   
17711                            m/zulu_dawn                0.0   

       tomatometer_rating audience_status  audience_rating  \
0                    49.0               0             53.0   
1                    87.0               1             64.0   
2                    67.0               0             53.0   
3                   100.0               1             97.0   
4                    89.0               1             74.0   
...                   ...             ...              ...   
17707                56.0               1             74.0   
17708                98.0               1             92.0   
17709                80.0               1             86.0   
17710                96.0               1             91.0   
17711                50.0               1             62.0   

       Action & Adventure  Comedy  Drama  Science Fiction & Fantasy  Romance  \
0                       1       1      1                          1        0   
1                       0       1      0                          0        0   
2                       0       1      0                          0        1   
3                       0       0      1                          0        0   
4                       1       0      1                          0        0   
...                   ...     ...    ...                        ...      ...   
17707                   0       0      1                          0        0   
17708                   1       1      0                          0        0   
17709                   1       0      1                          0        0   
17710                   0       0      1                          0        0   
17711                   1       0      1                          0        0   

       ...  Television  Cult Movies  Anime & Manga  Gay & Lesbian  \
0      ...           0            0              0              0   
1      ...           0            0              0              0   
2      ...           0            0              0              0   
3      ...           0            0              0              0   
4      ...           0            0              0              0   
...    ...         ...          ...            ...            ...   
17707  ...           0            0              0              0   
17708  ...           0            0              0              0   
17709  ...           0            0              0              0   
17710  ...           0            0              0              0   
17711  ...           0            0              0              0   

       content_rating_G  content_rating_NC17  content_rating_NR  \
0                     0                    0                  0   
1                     0                    0                  0   
2                     0                    0                  0   
3                     0                    0                  1   
4                     1                    0                  0   
...                 ...                  ...                ...   
17707                 0                    0                  0   
17708                 0                    0                  0   
17709                 0                    0                  1   
17710         

In [14]:
df[used_features].isna().sum().sum()

0

In [15]:
print(df[used_features].to_numpy().shape)
print(df[used_features].to_numpy())

(17255, 31)
[[0.0 49.0 0 ... 1 1 0]
 [2.0 87.0 1 ... 0 0 1]
 [1.0 67.0 0 ... 0 0 1]
 ...
 [1.0 80.0 1 ... 0 0 0]
 [1.0 96.0 1 ... 1 1 0]
 [0.0 50.0 1 ... 1 1 0]]


## Save data

In [16]:
df[ ['rotten_tomatoes_link']+used_features ].to_csv('../data/movies.csv',index=False)